/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedCallStudioRouteImport } from './routes/_authenticated/call-studio'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedNumbersRouteImport } from './routes/_authenticated/numbers'
import { Route as AuthenticatedVoiceModelsRouteImport } from './routes/_authenticated/voice-models'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicProcessAudioRouteImport } from './routes/api/public/process-audio'
import { Route as ApiPublicTranslateRouteImport } from './routes/api/public/translate'
import { Route as ApiPublicTwilioOutboundRouteImport } from './routes/api/public/twilio/outbound'
import { Route as ApiPublicTwilioSmsRouteImport } from './routes/api/public/twilio/sms'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio/status'
import { Route as ApiPublicTwilioTranscriptionRouteImport } from './routes/api/public/twilio/transcription'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCallStudioRoute = AuthenticatedCallStudioRouteImport.update({
  id: '/call-studio',
  path: '/call-studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNumbersRoute = AuthenticatedNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoiceModelsRoute =
  AuthenticatedVoiceModelsRouteImport.update({
    id: '/voice-models',
    path: '/voice-models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessAudioRoute = ApiPublicProcessAudioRouteImport.update({
  id: '/api/public/process-audio',
  path: '/api/public/process-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranslateRoute = ApiPublicTranslateRouteImport.update({
  id: '/api/public/translate',
  path: '/api/public/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioOutboundRoute = ApiPublicTwilioOutboundRouteImport.update({
  id: '/api/public/twilio/outbound',
  path: '/api/public/twilio/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSmsRoute = ApiPublicTwilioSmsRouteImport.update({
  id: '/api/public/twilio/sms',
  path: '/api/public/twilio/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio/status',
  path: '/api/public/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioTranscriptionRoute =
  ApiPublicTwilioTranscriptionRouteImport.update({
    id: '/api/public/twilio/transcription',
    path: '/api/public/twilio/transcription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/call-studio': typeof AuthenticatedCallStudioRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/voice-models': typeof AuthenticatedVoiceModelsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/process-audio': typeof ApiPublicProcessAudioRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/twilio/outbound': typeof ApiPublicTwilioOutboundRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/transcription': typeof ApiPublicTwilioTranscriptionRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/call-studio': typeof AuthenticatedCallStudioRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/voice-models': typeof AuthenticatedVoiceModelsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/process-audio': typeof ApiPublicProcessAudioRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/twilio/outbound': typeof ApiPublicTwilioOutboundRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/transcription': typeof ApiPublicTwilioTranscriptionRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/api-reference': typeof ApiReferenceRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/call-studio': typeof AuthenticatedCallStudioRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/numbers': typeof AuthenticatedNumbersRoute
  '/_authenticated/voice-models': typeof AuthenticatedVoiceModelsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/process-audio': typeof ApiPublicProcessAudioRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/twilio/outbound': typeof ApiPublicTwilioOutboundRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/transcription': typeof ApiPublicTwilioTranscriptionRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-reference'
    | '/contact'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/call-studio'
    | '/history'
    | '/numbers'
    | '/voice-models'
    | '/api/public/health'
    | '/api/public/process-audio'
    | '/api/public/translate'
    | '/api/public/twilio/outbound'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/status'
    | '/api/public/twilio/transcription'
    | '/api/public/twilio/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-reference'
    | '/contact'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/call-studio'
    | '/history'
    | '/numbers'
    | '/voice-models'
    | '/api/public/health'
    | '/api/public/process-audio'
    | '/api/public/translate'
    | '/api/public/twilio/outbound'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/status'
    | '/api/public/twilio/transcription'
    | '/api/public/twilio/voice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/api-reference'
    | '/contact'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/call-studio'
    | '/_authenticated/history'
    | '/_authenticated/numbers'
    | '/_authenticated/voice-models'
    | '/api/public/health'
    | '/api/public/process-audio'
    | '/api/public/translate'
    | '/api/public/twilio/outbound'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/status'
    | '/api/public/twilio/transcription'
    | '/api/public/twilio/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiReferenceRoute: typeof ApiReferenceRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicProcessAudioRoute: typeof ApiPublicProcessAudioRoute
  ApiPublicTranslateRoute: typeof ApiPublicTranslateRoute
  ApiPublicTwilioOutboundRoute: typeof ApiPublicTwilioOutboundRoute
  ApiPublicTwilioSmsRoute: typeof ApiPublicTwilioSmsRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioTranscriptionRoute: typeof ApiPublicTwilioTranscriptionRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/call-studio': {
      id: '/_authenticated/call-studio'
      path: '/call-studio'
      fullPath: '/call-studio'
      preLoaderRoute: typeof AuthenticatedCallStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/numbers': {
      id: '/_authenticated/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof AuthenticatedNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voice-models': {
      id: '/_authenticated/voice-models'
      path: '/voice-models'
      fullPath: '/voice-models'
      preLoaderRoute: typeof AuthenticatedVoiceModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-audio': {
      id: '/api/public/process-audio'
      path: '/api/public/process-audio'
      fullPath: '/api/public/process-audio'
      preLoaderRoute: typeof ApiPublicProcessAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/translate': {
      id: '/api/public/translate'
      path: '/api/public/translate'
      fullPath: '/api/public/translate'
      preLoaderRoute: typeof ApiPublicTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/outbound': {
      id: '/api/public/twilio/outbound'
      path: '/api/public/twilio/outbound'
      fullPath: '/api/public/twilio/outbound'
      preLoaderRoute: typeof ApiPublicTwilioOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms': {
      id: '/api/public/twilio/sms'
      path: '/api/public/twilio/sms'
      fullPath: '/api/public/twilio/sms'
      preLoaderRoute: typeof ApiPublicTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/status': {
      id: '/api/public/twilio/status'
      path: '/api/public/twilio/status'
      fullPath: '/api/public/twilio/status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/transcription': {
      id: '/api/public/twilio/transcription'
      path: '/api/public/twilio/transcription'
      fullPath: '/api/public/twilio/transcription'
      preLoaderRoute: typeof ApiPublicTwilioTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCallStudioRoute: typeof AuthenticatedCallStudioRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNumbersRoute: typeof AuthenticatedNumbersRoute
  AuthenticatedVoiceModelsRoute: typeof AuthenticatedVoiceModelsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCallStudioRoute: AuthenticatedCallStudioRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNumbersRoute: AuthenticatedNumbersRoute,
  AuthenticatedVoiceModelsRoute: AuthenticatedVoiceModelsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiReferenceRoute: ApiReferenceRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicProcessAudioRoute: ApiPublicProcessAudioRoute,
  ApiPublicTranslateRoute: ApiPublicTranslateRoute,
  ApiPublicTwilioOutboundRoute: ApiPublicTwilioOutboundRoute,
  ApiPublicTwilioSmsRoute: ApiPublicTwilioSmsRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioTranscriptionRoute: ApiPublicTwilioTranscriptionRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
